info:
  name: Get Argo CD Application Link
  type: http
  seq: 24
  tags:
    - v1
    - Argo CD

http:
  method: GET
  url: "{{baseUrl}}/:orgaId/api/spx-ctrl/:az/:projectId/argo-link/:kind/:effectiveId"
  headers:
    - name: Authorization
      value: "{{apiKey}}"
      description: Access token used to check user access in Superphenix API.
  params:
    - name: orgaId
      value: ""
      type: path
      description: Organization ID
    - name: az
      value: ""
      type: path
      description: AZ Code
    - name: projectId
      value: ""
      type: path
      description: Project ID
    - name: kind
      value: ""
      type: path
      description: Resource kind (kaas, baas, iaas)
    - name: effectiveId
      value: ""
      type: path
      description: Effective ID of the resource
  auth:
    type: apikey
    key: Authorization
    value: "{{apiKey}}"
    placement: header

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: 200 Response
    description: Argo CD Link
    request:
      url: "{{baseUrl}}/:orgaId/api/spx-ctrl/:az/:projectId/argo-link/:kind/:effectiveId"
      method: GET
      headers:
        - name: Authorization
          value: "{{apiKey}}"
          description: Access token used to check user access in Superphenix API.
      params:
        - name: orgaId
          value: ""
          type: path
          description: Organization ID
        - name: az
          value: ""
          type: path
          description: AZ Code
        - name: projectId
          value: ""
          type: path
          description: Project ID
        - name: kind
          value: ""
          type: path
          description: Resource kind (kaas, baas, iaas)
        - name: effectiveId
          value: ""
          type: path
          description: Effective ID of the resource
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "link": ""
          }
  - name: 400 Response
    description: Bad Request
    request:
      url: "{{baseUrl}}/:orgaId/api/spx-ctrl/:az/:projectId/argo-link/:kind/:effectiveId"
      method: GET
      headers:
        - name: Authorization
          value: "{{apiKey}}"
          description: Access token used to check user access in Superphenix API.
      params:
        - name: orgaId
          value: ""
          type: path
          description: Organization ID
        - name: az
          value: ""
          type: path
          description: AZ Code
        - name: projectId
          value: ""
          type: path
          description: Project ID
        - name: kind
          value: ""
          type: path
          description: Resource kind (kaas, baas, iaas)
        - name: effectiveId
          value: ""
          type: path
          description: Effective ID of the resource
    response:
      status: 400
      statusText: Bad Request
      body:
        type: text
        data: ""
  - name: 404 Response
    description: Not Found
    request:
      url: "{{baseUrl}}/:orgaId/api/spx-ctrl/:az/:projectId/argo-link/:kind/:effectiveId"
      method: GET
      headers:
        - name: Authorization
          value: "{{apiKey}}"
          description: Access token used to check user access in Superphenix API.
      params:
        - name: orgaId
          value: ""
          type: path
          description: Organization ID
        - name: az
          value: ""
          type: path
          description: AZ Code
        - name: projectId
          value: ""
          type: path
          description: Project ID
        - name: kind
          value: ""
          type: path
          description: Resource kind (kaas, baas, iaas)
        - name: effectiveId
          value: ""
          type: path
          description: Effective ID of the resource
    response:
      status: 404
      statusText: Not Found
      body:
        type: text
        data: ""
  - name: 500 Response
    description: Internal Server Error
    request:
      url: "{{baseUrl}}/:orgaId/api/spx-ctrl/:az/:projectId/argo-link/:kind/:effectiveId"
      method: GET
      headers:
        - name: Authorization
          value: "{{apiKey}}"
          description: Access token used to check user access in Superphenix API.
      params:
        - name: orgaId
          value: ""
          type: path
          description: Organization ID
        - name: az
          value: ""
          type: path
          description: AZ Code
        - name: projectId
          value: ""
          type: path
          description: Project ID
        - name: kind
          value: ""
          type: path
          description: Resource kind (kaas, baas, iaas)
        - name: effectiveId
          value: ""
          type: path
          description: Effective ID of the resource
    response:
      status: 500
      statusText: Internal Server Error
      body:
        type: text
        data: ""

docs: Returns the Argo CD UI link for a KaaS, BaaS or IaaS resource
